### PR TITLE
CORE-535: added a general purpose way to conditionally add a where cl…

### PR DESCRIPTION
**Pull request by slr71**
…ause to a query

### CODE REVIEW

**Review by ash3rz — APPROVED** [review]
I had to look up what `` ` ``  and `~` did, but it makes sense now 😄 
LGTM :shipit:

**Comment by slr71** [comment]
> I had to look up what `` ` `` and `~` did, but it makes sense now 😄
> LGTM :shipit:

Thanks for the review! Don't feel bad about having to look up the syntax. I have to look it up again every time I define a macro. 😆

**Comment by slr71** [comment]
Thanks again for the review!

**Review by psarando — COMMENTED** [review]
🎉

**Comment by slr71** [comment]
Thanks! I'm looking forward to having this macro available. This will eliminate the need for a lot of small functions that I used to write specifically for things like this.

**Comment by psarando** [comment]
Yep, same here 👍

**Pull request merged**
